name: Delete Azure Slot
on:
  pull_request:
    branches:
    - main
    - dev
    types: [closed]
    
env:
  AZURE_WEBAPP_NAME: RuneFlipperServer
  AZURE_RESOURCE_GROUP: rf-ResourceGroup
  
jobs:
  delete_slot:
    runs-on: ubuntu-latest
    
    steps:
    - name: login to AzureCLI
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B2DE6C837834F37907FC969C525FA1E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF198E71C24549FE9BFD86DC3E3FEE5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_87E470DCE23042CD9550F8159D539922 }}
          
    - name: Delete Azure Slot
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az webapp deployment slot delete --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --slot pr-${{ github.event.pull_request.number }}
