name: Deploy PR to Slot
on:
  pull_request:
    branches:
    - main
    - dev
env:
  AZURE_WEBAPP_NAME: RuneFlipperServer
  SLOT_NAME: pr-${{ github.event.number }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore 

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
        
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest
    
    steps:
    - name: login to AzureCLI
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B2DE6C837834F37907FC969C525FA1E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF198E71C24549FE9BFD86DC3E3FEE5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_87E470DCE23042CD9550F8159D539922 }}
          
    - name: Create Azure Slot
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az webapp deployment slot create --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rf-ResourceGroup --slot ${{ env.SLOT_NAME }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    
    steps:
    - name: login to Azure
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B2DE6C837834F37907FC969C525FA1E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF198E71C24549FE9BFD86DC3E3FEE5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_87E470DCE23042CD9550F8159D539922 }}
        
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        
    - name: Deploy to Azure WebApp Slot
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'RuneFlipperServer'
        package: .
        slot-name: ${{ env.SLOT_NAME }}
