name: Deploy PR to Slot
on:
  pull_request:
    branches:
    - main
    - dev
env:
  AZURE_WEBAPP_NAME: RuneFlipperServer
  SLOT_NAME: pr-${{ github.event.number }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore 

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
        
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: login to AzureCLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Create Azure Slot
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az webapp deployment slot create --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rf-ResourceGroup --slot ${{ env.SLOT_NAME }}

    - name: Wait for slot to be ready
      run: sleep 10

    - name: Set environment variable for Azure Slot
      run: |
        az webapp config connection-string set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rf-ResourceGroup --slot ${{ env.SLOT_NAME }} --settings RuneFlipper:Prod=${{ secrets.DEV_CONNECTIONSTRING }} --connection-string-type PostgreSQL
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    
    steps:
    - name: login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        
    - name: Deploy to Azure WebApp Slot
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'RuneFlipperServer'
        package: .
        slot-name: ${{ env.SLOT_NAME }}
