name: Deploy PR to Slot

on:
  pull_request:
    branches:
    - main
    - dev

env:
  AZURE_WEBAPP_NAME: RuneFlipperServer
  SLOT_NAME: pr-${{ github.event.number }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore ./src/RuneFlipper.Server

      - name: Build with dotnet
        run: dotnet build ./src/RuneFlipper.Server --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/RuneFlipper.Server --configuration Release --no-restore --verbosity normal

      - name: dotnet publish
        run: dotnet publish ./src/RuneFlipper.Server --configuration Release --no-restore --output './publish'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish
        
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: login to AzureCLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Create Azure Slot
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az webapp deployment slot create --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rf-ResourceGroup --slot ${{ env.SLOT_NAME }}

    - name: Set environment variable for Azure Slot
      run: |
        az webapp config connection-string set -g rf-ResourceGroup -n ${{ env.AZURE_WEBAPP_NAME }} -s ${{ env.SLOT_NAME }} -t custom --settings "RuneFlipperDb=${{ secrets.DEV_CONNECTIONSTRING }}"
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    
    steps:
    - name: login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
         
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ./publish
        
    - name: Deploy to Azure WebApp Slot
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'RuneFlipperServer'
        package: ./publish
        slot-name: ${{ env.SLOT_NAME }}
