name: Build/Test Pull Requests

on:
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build ./src/RuneFlipper.Server --configuration Release --no-restore

      - name: Test
        run: dotnet test ./test/RuneFlipper.Server.Test --configuration Release --no-restore